nohup: ignoring input
/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "tools/train-rescue.py", line 23, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/__init__.py", line 1, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/apis/inference.py", line 8, in <module>
    from mmseg.models import build_segmentor
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/__init__.py", line 2, in <module>
    from .fast_scnn import FastSCNN
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/backbones/fast_scnn.py", line 6, in <module>
    from mmseg.models.decode_heads.psp_head import PPM
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/__init__.py", line 16, in <module>
    from .point_head import PointHead
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmseg/models/decode_heads/point_head.py", line 6, in <module>
    from mmcv.ops import point_sample
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2983520) of binary: /home/zel220/anaconda3/envs/dual_teacher_new/bin/python
Traceback (most recent call last):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train-rescue.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2983521)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2983522)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2983523)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2983524)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 2983525)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 2983526)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 2983527)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-16_00:31:39
  host      : bina01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2983520)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
