nohup: ignoring input
/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)Traceback (most recent call last):

  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
Traceback (most recent call last):
  File "tools/train-rescue.py", line 16, in <module>
    import mmcv
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/__init__.py", line 4, in <module>
    from .fileio import *
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/__init__.py", line 2, in <module>
    from .file_client import BaseStorageBackend, FileClient
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/fileio/file_client.py", line 15, in <module>
    from mmcv.utils.misc import has_method
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/__init__.py", line 39, in <module>
    from .env import collect_env
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/mmcv/utils/env.py", line 9, in <module>
    import cv2
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 40, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2979270) of binary: /home/zel220/anaconda3/envs/dual_teacher_new/bin/python
Traceback (most recent call last):
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zel220/anaconda3/envs/dual_teacher_new/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train-rescue.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 2979271)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 2979272)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 2979273)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 2979274)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 2979275)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 2979276)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 2979277)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-16_00:28:42
  host      : bina01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2979270)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
